services:
  - type: web
    name: smartify
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        value: please-set-a-secure-secret-key
